name: Build MMUPy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write

jobs:

  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 PyInstaller

      - name: Build
        run: |
          pyinstaller `
            --noconfirm `
            --clean `
            --onefile `
            --windowed `
            --name MMUPy `
            --paths . `
            --collect-all PySide6 `
            --collect-submodules gui `
            --collect-submodules core `
            main.py

      - name: Check build
        run: |
          dir dist

      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          name: MMUPy-Windows
          path: dist/MMUPy.exe


  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 PyInstaller

      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \
            libgl1 \
            libxkbcommon-x11-0 \
            libdbus-1-3

      - name: Build
        run: |
          pyinstaller \
            --noconfirm \
            --clean \
            --onefile \
            --windowed \
            --name MMUPy \
            --paths . \
            --collect-all PySide6 \
            --collect-submodules gui \
            --collect-submodules core \
            main.py

      - name: Check build
        run: |
          ls -lah dist/

      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          name: MMUPy-Linux
          path: dist/MMUPy


  macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6 PyInstaller

      - name: Build
        run: |
          pyinstaller \
            --noconfirm \
            --clean \
            --windowed \
            --name MMUPy \
            --paths . \
            --collect-all PySide6 \
            --collect-submodules gui \
            --collect-submodules core \
            main.py

      - name: Create ZIP
        run: |
          cd dist
          zip -r ../MMUPy-macOS.zip MMUPy.app

      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          name: MMUPy-macOS
          path: MMUPy-macOS.zip